version: '3.7'

services:
  nodejs-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    image: nodejs-starter-test
    container_name: nodejs-starter-test
    environment:
      - MONGO_URI=mongodb://mongo:27017/node-starter-test
