name: Node.js CI CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15]
        mongodb-version: [4.2]

    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          VERSION=${GITHUB_SHA::8} make docker-build
          VERSION=${GITHUB_SHA::8} make docker-push

      - name: Verify Terraform version
        run: make terraform-version

      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make terraform-init
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: Start MongoDB v${{ matrix.mongodb-version }}
      #   uses: supercharge/mongodb-github-action@1.2.0
      #   with:
      #     mongodb-version: ${{ matrix.mongodb-version }}

      # - run: npm install
      # - run: npm test
      #   env:
      #     MONGO_URI: ${{secrets.MONGO_URI}}
